name: develop CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Save node_modules as artifact
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Download node_modules artifact
        uses: actions/download-artifact@v2
        with:
          name: node_modules

      - name: Run Cypress tests and generate video
        run: npm run register-dev

      - name: Upload Cypress video artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos

  report:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download Cypress video artifacts
        uses: actions/download-artifact@v2
        with:
          name: cypress-videos

      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/videos